version: "3"

services:

  ECommerceDataBase:
    image: mysql:8.0
    container_name: ECommerceDataBase
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_MAPPING_PORT}:${DATABASE_DEFAULT_PORT}"
    volumes:
      - ./ECommerceDataBase/data:/var/lib/mysql
    networks:
      - ECommerceAppNetwork


  ECommerceRestApi:
    image: hamzabekkaoui/ecommerce-restapi:latest
    container_name: ECommerceRestApi
    ports:
      - "${RESTAPI_MAPPING_PORT}:${RESTAPI_DEFAULT_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECURITY_JWT_SECRET_KEY: ${SECURITY_JWT_SECRET_KEY}
      SERVER_PORT: ${RESTAPI_DEFAULT_PORT}
    depends_on:
      - ECommerceDataBase
    networks:
      - ECommerceAppNetwork


networks:
  ECommerceAppNetwork:
    driver: bridge

